# Generated by Django 5.2.7 on 2025-10-27 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BIM', 'Bachelor in Information Management'), ('BCA', 'Bachelor in Computer Application'), ('CSIT', 'BSc. Computer Science and Information Technology')], max_length=10)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester'), ('Third', 'Third Semester'), ('Fourth', 'Fourth Semester'), ('Fifth', 'Fifth Semester'), ('Sixth', 'Sixth Semester'), ('Seventh', 'Seventh Semester'), ('Eighth', 'Eighth Semester')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='Files')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
